# -*- coding: utf-8 -*-
"""Supermarket Data Anaysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DFVQXh2LF7QKUXzyMHZfCtk4JTPAcnAf
"""

import pandas as pd

cust_cols = ['custno' ,'firstname' , 'lastname' ,'gender' , 'age' ,'profession' ,'contactNo' ,
'emailId' ,'city' , 'state' ,'isActive' ,'createdDate' , 'UpdatedDate']

prod_cols = ['productno', 'productName', 'Description', 'isActive','createdDate', 'UpdatedDate' ]
trans_cols = ['txnno','txndate','custno','amount','productno','spendby']

from google.colab import files
datafile = files.upload()

ls

cust_csv_s1 = pd.read_csv('customers.csv')

cust_csv_s1.columns=['custno' ,'firstname' , 'lastname' ,'gender' , 'age' ,'profession' ,'contactNo' ,
'emailId' ,'city' , 'state' ,'isActive' ,'createdDate' , 'UpdatedDate']

cust_csv_s1.head()

prod_csv_s1 = pd.read_csv('products.csv', names=prod_cols)
prod_csv_s1.head()

trans_csv_s1 = pd.read_csv('transactions.csv', names=trans_cols)
trans_csv_s1.head()

# Usecase-2
#trans_csv_s1.groupby('custno').filter(lambda trans_csv_s1:trans_csv_s1['custno'].count()>3)['custno'].unique()
trans_csv_s1.groupby('custno').filter(lambda trans_csv_s1:trans_csv_s1['custno'].count()>3)['custno'].unique()

# Usecase-3
trans_csv_s1['productno'].value_counts().head()

#Usecase-4 Display top 5 transactions amount from CSV_s1
trans_csv_s1.sort_values(by = "amount",ascending=False).head()

#Usecase-5 Display distinct professions from CSV_s1
cust_csv_s1["profession"].unique()

# Usecase-6 Display highest age in CSV_s1 customer’s dataset
cust_csv_s1['age'].max()

# Usecase-7 Display custno, gender, age, profession, contactno, productno, productName,txndate, spendby, amount from CSV_s1 for custno = 923
a = pd.merge(pd.merge(trans_csv_s1[trans_csv_s1['custno'] == 923], prod_csv_s1, on='productno', how='inner'), cust_csv_s1, on='custno', how='inner')

A=customers[customers['custno']==923]
df=pd.merge(A,transactions,on='custno')
df1=pd.merge(df,products,on='productno')
df1[['custno', 'gender', 'age', 'profession', 'productno', 'contactNo','productName', 'txndate', 'spendby', 'amount']]

a

a[['custno','gender','age','profession','contactNo','productno','txndate','spendby','amount']]

print('Usecase-7 Display custno, gender, age, profession, contactno, productno, productName,txndate, spendby, amount from CSV_s1 for custno = 923')
df_1 = cust_csv_s1.merge(trans_csv_s1)
df_2 = df_1[df_1['custno']==923]
df_2 = df_2[['custno','gender','age','profession','contactNo','productno','txndate','spendby','amount']]
df_2.join(prod_csv_s1['productName'], on='productno', how='inner')

ls

pd.read

from google.colab import files
datafile = files.upload()

#Usecase-8 Load all three PSV (pipe separated values) dataset in Pandas Data frames and
#display first 5 records.
customers_psv_s2= pd.read_csv("customers.xml",sep= "|",names= cust_cols)
products_psv_s2= pd.read_csv("products.xml",sep= "|",names= prod_cols)
transactions_psv_s2= pd.read_csv("transactions.xml",sep= "|",names= trans_cols)

customers_psv_s2.head()

products_psv_s2.head()

transactions_psv_s2.head()

from google.colab import files
datafile = files.upload()

customers_json_s3= pd.read_json("customers.json",lines=True)
# products_json_s3= pd.read_json("products.json",lines=True)
 #transactions_json_s3= pd.read_json("transactions.json",lines=True)

customers_json_s3.head()

customers_json_s3.head()

from google.colab import files
x = files.upload()

import pandas as pd

import xml.etree.ElementTree as et

cust_xml_s4 = et.parse('products.xml')

root = cust_xml_s4.getroot()

root

df = pd.DataFrame(columns=["pno","name","isactive","describe"])
df

for tag in root:
    custno = tag.find("productno").text
    firstname = tag.find("productName").text
    gender = tag.find("isActive").text
    age = tag.find("Description").text
    df = df.append(pd.Series([custno,firstname,gender,age],index=["pno","name","isactive","describe"]),ignore_index=True)

df.head()